config_version = 12

[accessibility]
ui_scale = 1.2500000111758709

[audio]
enable_sounds = true
sound_volume = 0.75999998301267624

[bar]
order = [ "default", "Bar_side" ]

    [bar.Bar_side]
    auto_hide = true
    capsule = true
    center = [ "bar", "widget_2" ]
    enabled = true
    end = [ "recorder", "battery-threshold" ]
    margin_ends = 300
    position = "right"
    radius = 80
    reserve_space = false
    show_on_workspace_switch = false
    start = [ "widget", "keybinds" ]
    thickness = 41
    widget_spacing = 7

    [bar.default]
    background_opacity = 0.75999998301267624
    capsule = true
    capsule_fill = "primary"
    capsule_opacity = 0.19999999552965164
    center = [ "bar_3", "clock", "bar_2" ]
    contact_shadow = true
    end = [ "battery", "session" ]
    margin_ends = 500
    padding = 33
    radius = 80
    scale = 1.2500000111758709
    start = [ "gamermode", "workspaces" ]
    thickness = 41

[brightness]
minimum_brightness = 0.04999999888241291
sync_all_monitors = true

[calendar]
enabled = true

[control_center]
sidebar = "full"
sidebar_section = "full"

    [control_center.calendar]
    event_time_format = "{:%-I:%M:%S %p}"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "8bury/lid-guard:lid-guard-toggle"

    [[control_center.shortcuts]]
    type = "icefish/phone-connect:tile"

    [[control_center.shortcuts]]
    type = "noctalia/screen_recorder:toggle"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
active_opacity = 0.64999998547136784
active_scale = 0.65000000968575478
background_opacity = 0.669999985024333
enabled = true
icon_size = 50
inactive_opacity = 0.74999998323619366
inactive_scale = 0.7500000111758709
launcher_position = "start"
magnification_scale = 2.0
pinned = [ "foot", "nvtop", "btop", "zen", "discord", "org.vinegarhq.Sober" ]
radius = 80
reserve_space = false
smart_auto_hide = true

[hooks]
theme_mode_changed = "/home/kyu/.local/bin/kbd-color-sync"
wallpaper_changed = "/home/kyu/.local/bin/kbd-color-sync"

[idle]
behavior_order = [ "screen-off", "lock", "lock-and-suspend" ]
pre_action_fade_seconds = 3

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 240.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-2", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 971.0
    output = "eDP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.76000000000000001
        background_radius = 12.0
        center_password_text = true
        input_opacity = 0.67000000000000004
        input_radius = 32.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 224.0
    box_width = 368.0
    cx = 960.0
    cy = 600.0
    output = "eDP-2"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.67000000000000004
        center_text = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 160.0
    box_width = 368.0
    cx = 496.0
    cy = 952.0
    output = "eDP-2"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background_opacity = 0.67000000000000004
        hide_when_no_media = false
        layout = "horizontal"

[notification]
layer = "overlay"

[osd]
background_opacity = 0.669999985024333
position = "bottom_center"

    [osd.kinds]
    media = false

[plugin_settings."cleboost/hotspot"]
password = "linuxmogs"
ssid = "Kyu"

[plugin_settings."noctalia/screen_recorder"]
frame_rate = 120
video_qp = 20

[plugin_settings."yocraft/web-launcher"]
icon_provider = "duckduckgo"
links = [ "YouTube|https://youtube.com", "Gmail|https://mail.google.com" ]
notify = false

[plugins]
auto_update = true
enabled = [
    "icefish/phone-connect",
    "damian-ds7/battery-threshold",
    "tadomika_ari/config-swap",
    "imjustdoingmypart/niri-animations",
    "noctalia/screen_recorder",
    "nomadcxx/gamer-mode",
    "8bury/lid-guard",
    "noctalia/world_clock",
    "noctalia/translator",
    "cleboost/hotspot",
    "yocraft/web-launcher",
    "noctalia/timer",
    "kenn/keybind-cheatsheet"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
corner_radius_scale = 2.0
niri_overview_type_to_launch_enabled = true
password_style = "random"
screen_time_enabled = true
show_location = false
time_format = "{:%-I:%M:%S %p}"

    [shell.animation]
    speed = 0.7500000111758709

    [shell.greeter_sync]
    auto_sync = true
    privilege_command = "pkexec"

    [shell.panel]
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    confirm_region = true
    directory = "/home/kyu/Pictures/Screenshots"
    remember_last_region = true
    show_cursor = true

    [shell.session]
    show_shortcuts = false

[theme]
source = "wallpaper"
wallpaper_scheme = "dysfunctional"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "foot", "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "zen-browser", "discord", "heroiclauncher", "steam", "fastfetch" ]

[wallpaper]
transition = [ "fade" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/kyu/Pictures/Wallpapers/wallhaven-2eqjdy.png"

    [wallpaper.last]
    path = "/home/kyu/Pictures/Wallpapers/wallhaven-2eqjdy.png"

    [wallpaper.monitors.eDP-2]
    path = "/home/kyu/Pictures/Wallpapers/wallhaven-2eqjdy.png"

[weather]
refresh_minutes = 5

[widget.bar]
type = "icefish/phone-connect:bar"

[widget.bar_2]
type = "noctalia/world_clock:bar"

[widget.bar_3]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.battery-threshold]
type = "damian-ds7/battery-threshold:battery-threshold"

[widget.clock]
anchor = true
format = "{:%-I:%M:%S %p}"

[widget.gamermode]
type = "nomadcxx/gamer-mode:gamermode"

[widget.keybinds]
type = "kenn/keybind-cheatsheet:keybinds"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.widget]
type = "yuuto/arch-updater:widget"

[widget.widget_2]
type = "tadomika_ari/config-swap:widget"

[widget.workspaces]
show_labels = false