color0 #241240
color1 #fd4663
color2 #9a67e4
color3 #cb5cd6
color4 #d35fa4
color5 #b793ec
color6 #e196e9
color7 #f2f2f3
color8 #66606f
color9 #fd4663
color10 #9a67e4
color11 #cb5cd6
color12 #d35fa4
color13 #b793ec
color14 #e196e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b0d30
background            #1b0d30
foreground            #f2f2f3
selection_foreground  #b2afb6
selection_background  #241240
active_border_color   #9a67e4
inactive_border_color #241240
url_color             #9a67e4

active_tab_foreground   #1c1824
active_tab_background   #9a67e4
inactive_tab_foreground #b2afb6
inactive_tab_background #241240
cursor_trail_color      #b2afb6
